name: first_project_vsc
description: First project vsc
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

# #docregion dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  english_words: ^3.1.5
# #enddocregion dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0

flutter:
  uses-material-design: true